name: Docker Image CI  # Nom de l'action GitHub

on:
  workflow_run:
    workflows: [Docker Tests]
    types: [completed]

jobs:

  on-success:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4  # Récupération du code source du référentiel

      - name: Build the Docker image  # Nom de l'étape pour construire l'image Docker
        run: docker build ./App -t ${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:${{ github.sha }}  # Commande pour construire l'image Docker avec des tags spécifiques

      - name: Log in to Docker Registry  # Nom de l'étape pour se connecter au registre Docker
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin  # Commande pour se connecter au registre Docker en utilisant les secrets du référentiel

      - name: Push the Docker image  # Nom de l'étape pour pousser l'image Docker vers le registre
        run: docker push ${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:${{ github.sha }}  # Commande pour pousser l'image Docker vers le registre en utilisant les secrets du référentiel

      - name: Checkout code for the update
        uses: actions/checkout@v4
        with:
          ref: main
  
      - name: Update Deployment Image Tag  # Nom de l'étape dans le workflow GitHub Actions
        run: |  # Début de l'exécution d'un script shell
          sed -i "s|${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:.*|${{ secrets.DOCKER_USERNAME }}/projet-flask-v0.1:${{ github.sha }}|g" ./deployment/flask.yaml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
  
  on-failure:  # Job à exécuter en cas d'échec du workflow
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu la plus récente pour exécuter le job
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # Condition pour exécuter le job uniquement en cas d'échec du workflow
    
    steps:  # Étapes à exécuter dans le job
      - run: echo 'Le workflow ne s'est pas éxécuter car les tests ont échoués'  # Affichage d'un message en cas d'échec des tests